version: '3.2'
services:
  db:
    image: postgres:11.3
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: lxsft
    ports:
      - "5432:5432/tcp"

  app:
    image: fuzuligulmammadli/coding-task-lxsft:v1
    restart: always
    ports:
      - "8081:8080/tcp"
    environment:
      DB_HOST: "db"

volumes:
  db_data: