version: '3.2'
services:
  db:
    image: postgres:11.3
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: lxsft
    ports:
      - "5432:5432/tcp"

volumes:
  db_data: