spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/lxsft
    username: test
    password: 1234
  jpa:
    open-in-view: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: "false"
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: "true"
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: validate
    show-sql: "true"
  liquibase:
    enabled: true

app:
  timestamp-format: "ISO_LOCAL_DATE_TIME"